### ISSUE TITLE
[PM2][ERROR] Init system not found

### ISSUE THREAD

**Issue by ctoslab** [D3VL/L3MON#112]
**This is an issue with the**
- [x] Server
- [ ] Client
- [x] Other

**Describe the bug**

I installed all requirements but when i start the app i get an error please help

**To Reproduce**

C:\Users\ctOS\Desktop\Hacking\Android\L3MON>pm2 startup
[PM2][ERROR] Init system not found
C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\lib\API\Startup.js:210
      throw new Error('Init system not found');
      ^

Error: Init system not found
    at API.CLI.startup (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\lib\API\Startup.js:210:13)
    at Command.<anonymous> (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\lib\binaries\CLI.js:699:9)
    at Command.listener (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:310:20)
    at Command.parseArgs (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\node_modules\commander\index.js:474:21)
    at Timeout._onTimeout (C:\Users\ctOS\AppData\Roaming\npm\node_modules\pm2\lib\binaries\CLI.js:204:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

C:\Users\ctOS\Desktop\Hacking\Android\L3MON>
**Expected behavior**

**Server Issue (please complete the following information):**
 - OS: [Windows]
 - OS Version: [Windows 10]
 - Browser: [e.g. chrome, safari]

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [x] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
`pm2 startup` doesn't work in windows - please skip this step!
