### ISSUE TITLE
"Java not found" problem after switching to java-8-openjdk occured again.

### ISSUE THREAD

**Issue by sna8** [D3VL/L3MON#92]
Hello,

After the notification "Java not installed" when .apk is building, I have switched to java-8-openjdk version. 
This is the output from event log:

> 

14/04/2020, 15:36:35 => SUCCESS | Build Succeded!
14/04/2020, 15:36:32 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:26:20 => SUCCESS | Build Succeded!
14/04/2020, 15:26:17 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:21:25 => SUCCESS | Build Succeded!
14/04/2020, 15:21:21 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:19:02 => SUCCESS | Build Succeded!
14/04/2020, 15:18:58 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:10:58 => SUCCESS | Build Succeded!
14/04/2020, 15:10:55 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:10:29 => SUCCESS | Build Succeded!
14/04/2020, 15:10:26 => ERROR | Build Failed - Java Not Installed
14/04/2020, 15:03:42 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/home/g4busr/App/L3MON-v1.1.0/app/factory/sign.jar" "/home/g4busr/App/L3MON-v1.1.0/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
14/04/2020, 15:03:39 => ERROR | Build Failed - Java Not Installed

> 

I`m using Kali 2020.2

Thanks in advance!

**Comment by Enigma1024** [comment]
Same problem for me. What is your version of Java and your OS ? : 
Me, I'm on Kali Linux, my version of Java is : 
~# java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by Enigma1024** [comment]
I have installed on Windows Server and it's good. But we have bug with version of Java on Linux maybe only Kali Linux.

**Comment by rex007m** [comment]
if you have installed Java 8 
Then do this,
 ```
spawn.stderr.on('data', (data) => {
        //data = data.toString().split('\n')[0];
        var javaVersion = "1.8"; //new RegExp('java version').test(data) ? data.split(' ')[2].replace(/"/g, '') : false;
        //  var openJDKVersion = new RegExp('openjdk version').test(data) ? data.split(' ')[2].replace(/"/g, '') : false;
        //  if (javaVersion || openJDKVersion) {
            spawn.removeAllListeners();
            spawn.stderr.removeAllListeners();
            return callback(null, javaVersion);
      //  } else return callback("Java Not Installed" + data , undefined);
    });
```

Just Disable Auto version And feed Manual Version.
This trick works on kali 2020

**Comment by Jack-Rogers** [comment]
@rex007m  That's a bit of a sledgehammer approach! Here's the code I'm about to push in the latest release that should fix this

```Javascript
function javaversion(callback) {
    let spawn = cp.spawn('java', ['-version']);
    let output = "";
    spawn.on('error', (err) => callback("Unable to spawn Java - " + err, null));
    spawn.stderr.on('data', (data) => {
        output += data.toString();
    });
    spawn.on('close', function (code) {
        let javaIndex = output.indexOf('java version');
        let openJDKIndex = output.indexOf('openjdk version');
        let javaVersion = (javaIndex !== -1) ? output.substring(javaIndex, (javaIndex + 27)) : "";
        let openJDKVersion = (openJDKIndex !== -1) ? output.substring(openJDKIndex, (openJDKIndex + 27)) : "";
        if (javaVersion !== "" || openJDKVersion !== "") {
            if (javaVersion.includes("1.8.0") || openJDKVersion.includes("1.8.0")) {
                spawn.removeAllListeners();
                spawn.stderr.removeAllListeners();
                return callback(null, (javaVersion || openJDKVersion));
            } else return callback("Wrong Java Version Installed. Detected " + (javaVersion || openJDKVersion) + ". Please use Java 1.8.0", undefined);
        } else return callback("Java Not Installed", undefined);
    });
}
```

**Comment by Jack-Rogers** [comment]
V1.1.2 has now been released that hopefully fixes this issue, please update and try again!
https://github.com/D3VL/L3MON/releases/tag/1.1.2

**Comment by matiasst** [comment]
# Changing default Configuration java 11 to java OpenJDK-8
 update-alternatives --config java         
 type selection number 2
# Restarting the L3MON server
 pm2 restart all

**Comment by rex007m** [comment]
@Jack-Rogers Yeah problem is fixed now. (y)

**Comment by tgolais** [comment]
This code works for me

`function javaversion(callback) {
	let spawn = cp.spawn('java', ['-version']);
	let output = "";
	spawn.on('error', (err) => callback("Unable to spawn Java - " + err, null));

	spawn.stderr.on('data', (data) => {
		output += data.toString();
	});

	**// break the textblock into an array of lines
	var lines = output.split('\n');
	// remove one line, starting at the first position
	lines.splice(0,1);
	// join the array back into a single string
	var output = lines.join('\n');**

	spawn.on('close', function (code) {

		let javaIndex = output.indexOf('java version');

		let openJDKIndex = output.indexOf('openjdk version');

		let javaVersion = (javaIndex !== -1) ? output.substring(javaIndex, (javaIndex + 27)) : "";
		let openJDKVersion = (openJDKIndex !== -1) ? output.substring(openJDKIndex, (openJDKIndex + 27)) : "";
		
		if (javaVersion !== "" || openJDKVersion !== "") {
			if (javaVersion.includes("1.8.0") || openJDKVersion.includes("1.8.0")) {
				spawn.removeAllListeners();
				spawn.stderr.removeAllListeners();
				return callback(null, (javaVersion || openJDKVersion));
			} else return callback("Wrong Java Version Installed. Detected " + (javaVersion || openJDKVersion) + ". Please use Java 1.8.0", undefined);
		} else return callback("Java Not Installed", undefined);
	});
}`

**Comment by NasyxRakeeb2** [comment]
hello,
i installed l3mon latest ver on kali 2020.3 when i tried to build apk it showed java 11 can not be used then i switched to java8 now i am getting this error _**Unable to spawn java -Error:spawn java ENNOT**_
I saw upper sols. but i dont know wht to do with these codes.
